export class StateConstants {
    public static readonly states: any[] = [
        {typeValue: 'AL', caption: 'Alabama'},
        {typeValue: 'AK', caption: 'Alaska'},
        {typeValue: 'AR', caption: 'Arkansas'},
        {typeValue: 'AZ', caption: 'Arizona'},
        {typeValue: 'CA', caption: 'California'},
        {typeValue: 'CO', caption: 'Colorado'},
        {typeValue: 'CT', caption: 'Connecticut'},
        {typeValue: 'DE', caption: 'Delaware'},
        {typeValue: 'DC', caption: 'District of Columbia'},
        {typeValue: 'FL', caption: 'Florida'},
        {typeValue: 'GA', caption: 'Georgia'},
        {typeValue: 'HI', caption: 'Hawaii'},
        {typeValue: 'ID', caption: 'Idaho'},
        {typeValue: 'IL', caption: 'Illinois'},
        {typeValue: 'IN', caption: 'Indiana'},
        {typeValue: 'IA', caption: 'Iowa'},
        {typeValue: 'KS', caption: 'Kansas'},
        {typeValue: 'KY', caption: 'Kentucky'},
        {typeValue: 'LA', caption: 'Louisiana'},
        {typeValue: 'ME', caption: 'Maine'},
        {typeValue: 'MD', caption: 'Maryland'},
        {typeValue: 'MA', caption: 'Massachusetts'},
        {typeValue: 'MI', caption: 'Michigan'},
        {typeValue: 'MN', caption: 'Minnesota'},
        {typeValue: 'MS', caption: 'Mississippi'},
        {typeValue: 'MO', caption: 'Missouri'},
        {typeValue: 'MT', caption: 'Montana'},
        {typeValue: 'NE', caption: 'Nebraska'},
        {typeValue: 'NV', caption: 'Nevada'},
        {typeValue: 'NH', caption: 'New Hampshire'},
        {typeValue: 'NJ', caption: 'New Jersey'},
        {typeValue: 'NM', caption: 'New Mexico'},
        {typeValue: 'NY', caption: 'New York'},
        {typeValue: 'NC', caption: 'North Carolina'},
        {typeValue: 'ND', caption: 'Norht Dakota'},
        {typeValue: 'OH', caption: 'Ohio'},
        {typeValue: 'OK', caption: 'Oklahoma'},
        {typeValue: 'OR', caption: 'Oregon'},
        {typeValue: 'PA', caption: 'Pennsylvania'},
        {typeValue: 'RI', caption: 'Rhode Island'},
        {typeValue: 'SC', caption: 'South Carolina'},
        {typeValue: 'SD', caption: 'South Dakota'},
        {typeValue: 'TN', caption: 'Tennessee'},
        {typeValue: 'TX', caption: 'Texas'},
        {typeValue: 'UT', caption: 'Utah'},
        {typeValue: 'VT', caption: 'Vermont'},
        {typeValue: 'VA', caption: 'Virginia'},
        {typeValue: 'WA', caption: 'Washington'},
        {typeValue: 'WV', caption: 'West Virginia'},
        {typeValue: 'WI', caption: 'Wisconsin'},
        {typeValue: 'WY', caption: 'Wyoming'},
    ];
}
